config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get "/snakes", to: "snakes#index", as: "snakes"
  # get "/snakes/:snake_id", to: "snakes#show", as: "snake"
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :snakes do
    resources :bookings
    resources :reviews, only: [:new, :create, :show]
  end
  #   resources :bookings do
  #   resources :reviews, only: [:new, :create]
  # end
  get "/users/:user_id", to: "pages#show", as: "user"
  get "/users/:user_id/bookings", to: "bookings#user_show", as: "user_bookings"
  get "/users/:user_id/snakes", to: "snakes#user_show", as: "user_snakes"

  mount Attachinary::Engine => "/attachinary"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/snake.rb
  class Snake < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: ["Male", "Female", "Unknown"]}
  validates :available, presence: true
  validates :breed, presence: true
  has_attachment :photo
  after_validation :geocode, if: :address_changed?


  # We need a validator to make sure the price is greater than zero
  # validates :price, presence: true, greater_than_or_equal_to: 0

end

app/controllers/snakes_controller.rb
class SnakesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @snakes = Snake.all

    if current_user
      @snakes = @snakes.where.not(user_id: current_user.id).order(price: :desc)
    end

    if params[:search]
      if params[:search][:address].present? && params[:search][:proximity].present?
        @snakes = Snake.near(params[:search][:address], params[:search][:proximity].to_i)
      end
      if params[:search][:sex].present?
        @snakes = @snakes.where(sex: params[:search][:sex])
      end
      if params[:search][:price_lower].present? && params[:search][:price_upper].present?
        @snakes = @snakes.where("price > ?", params[:search][:price_lower]).where("price < ?", params[:search][:price_upper])
      end
    end

    @geo_snakes = @snakes.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@geo_snakes) do |snake, marker|
      marker.lat snake.latitude
      marker.lng snake.longitude
    end

  end

  def show
    @snake = Snake.find(params[:id])

    @reviews = @snake.reviews
    if Review.where(user: current_user, snake: @snake).last.nil?

#     @alert_message = "You are viewing #{@snake.name}"
#     @snake_coordinates = { lat: @snake.latitude, lng: @snake.longitude }
#     if !Review.where(:user => current_user).nil?
#       @review = Review.where(:user => current_user)
#     else

      @review = Review.new
    else
      @review = Review.where(user: current_user, snake: @snake).last
    end
  end

  def new
    snake_breeds = []
    Snake.all.each do |snake|
      snake_breeds << snake.breed
    end

    @breeds = snake_breeds.uniq.sort

    # @breeds = Snake.limit(5).select("breed").each { |breed| puts "#{breed}" }
  end

  def create
    @new_snake = Snake.new(snake_params)
    @new_snake.user = current_user
    @breeds = Snake.all.select("breed")
    if @new_snake.save
      redirect_to snake_path(@new_snake)
    end
  end

  def edit
    @snake = Snake.find(params[:id])
    if @snake.user == current_user
      @snake = Snake.find(params[:id])
    else
      redirect_to snake_path(@snake)
    end
  end

  def update
    @snake = Snake.find(params[:id])
    @snake.update(snake_params)
    if @snake.valid?
      redirect_to snake_path(@snake)
    else
      redirect_to edit_snake(@snake)
    end
  end

  def destroy
    if Snake.find(params[:id]).user == current_user
      @snake = Snake.find(params[:id])
      @snake.destroy
      # Redirect to list of user's snakes once that view has been built
      # redirect_to user_snake_path(current_user)
      # For now we'll redirect back to the main index of snakes
      redirect_to snakes_path
    end
  end

  def user_show
    current_user.snakes_booked_notifications = 0
    current_user.save
    @user = User.find(params[:user_id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def snake_params
    params.require(:snake).permit(:name, :breed, :sex, :available, :price, :photo, :address)
  end
end

app/helpers/snakes_helper.rb
module SnakesHelper

  def have_not_booked(snake)
    return true unless current_user
    snakes_youve_booked = []
    bookings = Booking.where(user_id: current_user.id)
    bookings.each do |i|
      snakes_youve_booked << i.snake.id
    end

    output = snakes_youve_booked.include?(snake.id) ? false : true
    return output
  end

end

app/views/snakes/destroy.js.erb
// $('[data-snake-id=<%= @snake.id %>]').slideUp();

app/views/snakes/edit.html.erb
<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>

<div class="show-wrapper">
  <div class="show-container">
    <div class="picture-title">
      <% if @snake.user == current_user %>
        <div class="show-tabs">
          <div class="show-buffer"></div>
          <% edit_snake = "<h3>Edit Snake</h3>" %>
          <% bookings_snake = "<h3>Snake's Bookings</h3>" %>
          <% view_snake = "<h3>View Snake</h3>" %>
          <%= link_to view_snake.html_safe, snake_path(@snake), class: "show-tab view-tab" %>
          <%= link_to edit_snake.html_safe, edit_snake_path(@snake), class: "show-tab edit-tab", id: "current-tab" %>
          <%= link_to bookings_snake.html_safe, snake_bookings_path(@snake), class: "show-tab bookings-tab" %>
        </div>
      <% end %>
      <% if @snake.photo %>
        <%= cl_image_tag @snake.photo.path, width: 300, height: 300, crop: :fill, class: "show-photo" %>
      <% end %>
      <div class="show-name">
        <h1><%= @snake.name %></h1>
      </div>
    </div>
    <div class="book-button">
      <% unless @snake.user == current_user %>
        <%= link_to "Book snake", new_snake_booking_path(@snake), class: "btn btn-danger" %>
      <% end %>
    </div>
    <div class="show-details">
      <div class="edit-snake-form">
        <div>
          <h2>Edit Your Snake</h2>
        </div>
        <%= simple_form_for @snake do |i| %>
          <%= i.error_notification %>
          <%= i.input :name, required: true, autofocus: true %>
          <%= i.input :sex, collection: ["Male", "Female", "Unknown"], required: true, autofocus: true %>
          <%= i.input :breed, required: true, autofocus: true %>
          <%= i.input :price, required: true, autofocus: true %>
          <%= i.input :available, as: :select, required: true, autofocus: true, label: "Available for rent immediately" %>
          <%= i.input :photo, as: :attachinary %>
          <%= i.submit %>
        <% end %>
        <br>
        <br>
        <%= link_to "Delete your snake", snake_path(@snake), class: "btn btn-danger", method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/snakes/index.html.erb
<div class="index-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>

<div class="text-center index-title">
  <h1>Rent Your Snake</h1>
</div>

<div class="snake-filter">
  <%= simple_form_for :search,  url: snakes_path , :method => :get, html: {class: 'form-inline'} do |f| %>
    <div class="snake-filter-form-items">
      <%= f.input :sex, collection: ["Male", "Female", "Unknown"],  required: false, label: "Sex:" %>
      <%= f.input :address, label: "Address:" %>
      <%= f.input :proximity, collection: [10, 25, 50, 100, 1000], label: "Within (km): " %>
      <%= f.input :price_lower, as: :integer, required: false, label: "Min" %>
      <%= f.input :price_upper, as: :integer, required: false, label: "Max" %>
      <%= f.submit "Catch a Snake!", class: "btn btn-danger"  %>
    </div>
  <% end %>
  <% if @snakes.blank? %>
    <h4>There are no snakes matching your search terms.</h4>
  <% end %>
  </div>
</div>


<div class="wrapper margin-up">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div id="map" style="width: 100%; height: 400px; margin: 30px auto;"></div>
      </div>
    </div>
    <% for i in 0...@snakes.length do %>
      <% if i % 3 == 0 %>
          <div class="row">
            <% for j in i..(i + 2) do %>
              <div class="col-xs-12 col-sm-4">
                <% snake = @snakes[j] %>
                <% unless snake.nil? %>
                  <% image_url = snake.photo.nil? ? image_path("th.jpeg") : cl_image_path(snake.photo.path, crop: :fit, class: "card- link")  %>
                  <%= link_to snake_path(snake) do %>
                    <div class="card temp" style="background-image: url(<%= image_url %>)">
                      <div class="card-opacity"></div>
                      <div class="card-category">
                        <h2><%= snake.name %></h2>
                      </div>
                      <div class="card-user">
                      </div>
                      <div class="card-description">
                        <h3><%= snake.breed %></h3>
                        <p><%= snake.sex %></p>
                      </div>
                      <div class="card-price">
                        <%= "#{snake.price}" + "$" %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
      <% end %>
    <% end %>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>



<style>

  .navbar-wagon {
    background: rgba(0, 0, 0, 0);
    position: absolute;
    box-shadow: 0 0 0 0 !important;
    width: 100%;
  }

</style>

app/views/snakes/new.html.erb
<div class="form-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>

<div class="new-snake-form">
  <div>
    <h2>Add Your Snake</h2>
  </div>
  <%= simple_form_for Snake.new do |i| %>
    <%= i.error_notification %>
    <%= i.input :name, required: true, autofocus: true %>
    <%= i.input :sex, required: true, autofocus: true, collection: ["Male", "Female", "Unknown"] %>
    <%= i.input :breed, required: true, autofocus: true %>
    <%= i.input :price, required: true, autofocus: true %>
    <%= i.input :available, as: :select, required: true, autofocus: true, label: "Available for rent immediately" %>
    <%= i.input :address, required: true, autofocus: true %>
    <%= i.input :photo, as: :attachinary %>
    <%= i.submit %>
  <% end %>
</div>

<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU"></script>
<% end %>

app/views/snakes/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>

<div class="show-wrapper">
  <div class="show-container">
    <div class="picture-title">
      <% if @snake.user == current_user %>
      <div class="show-tabs">
        <div class="show-buffer"></div>
        <% edit_snake = "<h3>Edit Snake</h3>" %>
        <% bookings_snake = "<h3>Snake's Bookings</h3>" %>
        <% view_snake = "<h3>View Snake</h3>" %>
        <%= link_to view_snake.html_safe, snake_path(@snake), class: "show-tab view-tab", id: "current-tab" %>
        <%= link_to edit_snake.html_safe, edit_snake_path(@snake), class: "show-tab edit-tab" %>
        <%= link_to bookings_snake.html_safe, snake_bookings_path(@snake), class: "show-tab bookings-tab" %>
      </div>
      <% end %>
      <% if @snake.photo %>
      <%= cl_image_tag @snake.photo.path, width: 300, height: 300, crop: :fill, class: "show-photo" %>
      <% end %>
      <div class="show-name">
        <h1><%= @snake.name %></h1>
      </div>
    </div>
    <div class="book-button">
      <% if @snake.user != current_user && have_not_booked(@snake) && current_user%>
      <%= link_to "Book snake", new_snake_booking_path(@snake), class: "btn btn-danger" %>
      <% elsif @snake.user != current_user && have_not_booked(@snake) == false %>

      <em><h3>You've Booked This Snake!</h3></em>
      <% elsif current_user == false %>
      <em><h3>Log in or sign up to book snakes</h3></em>

      <% end %>
    </div>
    <div class="show-details">
      <div class="detail-div">
        <h2>Breed:</h2>
        <h3 id="snake-breed"><%= @snake.breed %></h3>
        <% if @snake.breed.length > 17 %>
        <style>
          #snake-breed {
            font-size: 20px;
          }
        </style>
        <% elsif @snake.breed.length > 10 %>
        <style>
          #snake-breed {
            font-size: 25px;
          }
        </style>
        <% end %>
      </div>
      <div class="detail-div">
        <h2>Sex:</h2>
        <h3><%= @snake.sex %></h3>
      </div>
      <div class="detail-div">
        <h2>Price:</h2>
        <h3><%= @snake.price %></h3>
      </div>
      <div class="detail-div">
        <h2>Owner:</h2>
        <h3><%= link_to @snake.user.username, user_path(@snake.user) %></h3>
      </div>
      <div class="booking-info">


        <%#= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&sensor=false&maptype=roadmap&markers=color:red|#{@snake.address}" %>
        <h3>
          <%= pluralize @snake.reviews.size, "review" %>
        </h3>

        <div id="reviews">
        <% if @snake.reviews.blank? %>
              Be the first to leave a review for <%= @snake.name %>
          <% else %>
            <% @snake.reviews.each do |review| %>
              <%= render 'reviews/show', review: review %>
          <% end %>
          <% end %>
        </div>

          <% if current_user %>
          <%# link_to "My Snakes", user_snakes_path(current_user), class: "btn btn-danger" %>
              <br>
            <% if @snake.bookings == current_user.bookings %>
              <% if @reviews.empty? %>
                <%= render 'reviews/form', snake: @snake, review: @review %>
              <% end %>
            <% end %>
          <% else %>
              <em><h3>Log in or sign up to book snakes</h3></em>
          <% end %>


      </div>
    </div>
  </div>
</div>
<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).ready(function() {
var coord = <%= raw @snake_coordinates.to_json %>;
});
<% end %>
<% end %>

app/views/snakes/user_show.html.erb
<div class="user-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>


<div class="show-wrapper">
  <div class="show-container">
    <div class="picture-title">
      <div class="show-tabs">
        <% my_profile = "<h3>My Profile</h3>" %>
        <% edit_profile = "<h3>Edit Profile</h3>" %>
        <% my_bookings = "<h3>My Bookings #{booking_responses_notifications(current_user)}</h3>" %>
        <% my_snakes = "<h3>My Snakes #{snakes_booked_notifications(current_user)} </h3>" %>
        <%= link_to my_profile.html_safe, user_path(@user), class: "show-tab my-tab" %>
        <%= link_to edit_profile.html_safe, edit_user_registration_path, class: "show-tab edit-tab" %>
        <%= link_to my_bookings.html_safe, user_bookings_path(@user), class: "show-tab my-bookings-tab" %>
        <%= link_to my_snakes.html_safe, user_snakes_path(@user), class: "show-tab my-snakes-tab", id: "current-tab" %>
      </div>
      <div class="user-profile-picture">
        <% if @user.facebook_picture_url %>
          <%= cl_image_tag "https://graph.facebook.com/#{current_user.uid}/picture?type=large", crop: :fill %>
        <% end %>
      </div>
      <div class="show-name">
        <h1>Your Snakes</h1>
      </div>
    </div>
    <div class="show-details text-center">
      <% if @user.snakes.count.zero? %>
        <br>
        <br>
        <p>You have no snakes!</p>
        <%= link_to "... add some", new_snake_path, class: "btn btn-danger" %>
      <% else %>
        <% snakes = @user.snakes %>
        <% snakes = snakes.sort_by { |snake| snake.bookings.count } %>
        <% snakes.reverse.each do |i| %>
          <div class="my-snakes-card">
            <% if i.photo %>
              <div class="my-snake-photo">
                <%= cl_image_tag i.photo.path, width: 150, height: 150, crop: :fill, class: "my-snake-avater" %>
              </div>
            <% end %>
            <div class="my-snake-details">
              <p>Snake Name: <%= link_to i.name, snake_path(i) %></p>
              <% if i.bookings.count.zero? %>
                <p>No bookings</p>
                <br>
              <% else %>
                <p>Number of bookings: <%= i.bookings.count %></p>
                <%= link_to "View latest booking", snake_booking_path(i, i.bookings.order(:updated_at).reverse[0]), class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<style>

.show-details {
  width: 65% !important;
}

</style>