config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get "/snakes", to: "snakes#index", as: "snakes"
  # get "/snakes/:snake_id", to: "snakes#show", as: "snake"
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :snakes do
    resources :bookings
    resources :reviews, only: [:new, :create, :show]
  end
  #   resources :bookings do
  #   resources :reviews, only: [:new, :create]
  # end
  get "/users/:user_id", to: "pages#show", as: "user"
  get "/users/:user_id/bookings", to: "bookings#user_show", as: "user_bookings"
  get "/users/:user_id/snakes", to: "snakes#user_show", as: "user_snakes"

  mount Attachinary::Engine => "/attachinary"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(70, 173, 114, 0.3) 50%), url('http://res.cloudinary.com/dxvq7itog/image/upload/v1491861510/king-snake-snake-banded-red-47310_zjcc99.jpg');">
  <div>
    <h1 id="title">
      <% if current_user %>
        WELCOME BACK,
        <%= current_user.first_name.upcase %>
      <% else %>
        SLITHERZZZZ
      <% end %>
    </h1>
  </div>
  <div>
    <h2 id="subtitle">Rent Snakes With Us</h2>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 home-card">
      <a href="">
        <div class="snake-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dxvq7itog/image/upload/v1491861468/grass-snake-snake-serpentes-natrix-80474_wkjbt9.jpg');">
          <h1>Vipers</h1>
        </div>
      </a>
    </div>
    <div class="col-xs-12 col-sm-4 home-card">
      <a href="/snakes">
        <div class="snake-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dxvq7itog/image/upload/v1491861567/snake-animal-nature-toxic-46500_ywyjze.jpg');">
          <h1>VIEW ALL OUR SNAKES</h1>
        </div>
      </a>
    </div>
    <div class="col-xs-12 col-sm-4 home-card">
      <a href="">
        <div class="snake-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/dxvq7itog/image/upload/v1491861610/snake-rainbow-boa-reptile-scale_eqmahe.jpg');">
          <h1>Cobras</h1>
        </div>
      </a>
    </div>
  </div>
</div>

<style>

  .navbar-wagon {
    background: rgba(0, 0, 0, 0);
    position: absolute;
    box-shadow: 0 0 0 0 !important;
    width: 100%;
  }

  .session {
    color: white;
  }

</style>

app/views/pages/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12">

      <div class="text-center">
      <h1>Index All Snakes Public</h1>
        <ul>
          <% @snake.each do |snake| %>
            <li><%= link_to snake.name, snake_path(snake) %></li>
          <% end %>
        </ul>
        <%= link_to "Return Home", pages_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/my_profile.html.erb
<div class="user-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>

<div class="show-wrapper">
  <div class="show-container">
    <div class="picture-title">
      <div class="show-tabs">
        <% my_profile = "<h3>My Profile</h3>" %>
        <% edit_profile = "<h3>Edit Profile</h3>" %>
        <% my_bookings = "<h3>My Bookings #{booking_responses_notifications(current_user)}</h3>" %>
        <% my_snakes = "<h3>My Snakes #{snakes_booked_notifications(current_user)} </h3>" %>
        <%= link_to my_profile.html_safe, user_path(@user), class: "show-tab my-tab", id: "current-tab" %>
        <%= link_to edit_profile.html_safe, edit_user_registration_path, class: "show-tab edit-tab" %>
        <%= link_to my_bookings.html_safe, user_bookings_path(@user), class: "show-tab my-bookings-tab" %>
        <%= link_to my_snakes.html_safe, user_snakes_path(@user), class: "show-tab my-snakes-tab" %>
      </div>
      <div class="user-profile-picture">
        <% if @user.facebook_picture_url %>
          <%= cl_image_tag "https://graph.facebook.com/#{current_user.uid}/picture?type=large", crop: :fill %>
        <% end %>
      </div>
      <div class="show-name">
        <h1><%= @user.username %></h1>
      </div>
    </div>
    <div class="show-details">
      <div class="user-details-box">
        <h3>Full Name:</h3>
        <p><%= @user.first_name %> <%= @user.last_name %></p>
        <br>
        <h3>Bio:</h3>
        <p class="bio"><%= @user.bio %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/user_profile.html.erb
<div class="user-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(70, 173, 114,0.6) 50%), url('https://img.clipartfox.com/41ae2ca010239733a6ee136773a2c4b1_amazon-forest-amazon-forest-clipart_1440-900.jpeg');">
</div>

<div class="show-wrapper">
  <div class="show-container">
    <div class="picture-title">
      <% if @user.facebook_picture_url %>
        <%= cl_image_tag @user.facebook_picture_url, width: 300, height: 300, crop: :fill %>
      <% end %>
      <div class="show-name">
        <h1><%= @user.username %></h1>
      </div>
    </div>
    <div class="show-details">
      <div class="user-details-box">
        <h3>Full Name:</h3>
        <p class="name"><%= @user.first_name %> <%= @user.last_name %></p>
        <h3>Bio:</h3>
        <p class="bio"><%= @user.bio %></p>
      </div>
    </div>
  </div>
</div>